package com.dt002g.reviewapplication.frontend.service;

import java.util.List;

public interface GetNumberOfAdjectivesByNameInReviewRatingAndMedianScoreRangeMatrixCallBack {
    void processGetNumberOfAdjectivesByNameInReviewRatingAndMedianScoreRangeMatrixCallBack(List<AdjectiveByReviewRatingAndScoreBackendEntity> response);
}
